services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18" # We found this Postgres image on "docker hub"
    env_file:
      - ../.env.development # This makes Postgres from Container & from Outside share the same "variables" ("docker hub"/Postgres image has a list of all needed variables)
    ports:
      - "5432:5432" # host:container (EXPOSING PORTS TO OUTSIDE THE CONTAINER)
