services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env # This makes Postgres from Container & from Outside share the same "variables"
    ports:
      - "5432:5432" # host:container (EXPOSING PORTS TO OUTSIDE THE CONTAINER)