name: Linting
on: pull_request

jobs:
  prittier:
    name: Prettier
    runs-on: ubuntu-latest # Not necessary (?)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/hydrogen"

      - run: npm ci
      - run: npm run lint:prettier:check
